# Generated by Django 5.0.6 on 2024-07-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_carritocompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompra',
            name='user',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='AlgunaClase',
        ),
        migrations.DeleteModel(
            name='CarritoCompra',
        ),
    ]
