# Generated by Django 5.0.6 on 2024-07-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_remove_carritocompra_user_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='productos/'),
        ),
    ]
