# Generated by Django 5.0.6 on 2024-07-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_cliente_compra_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(default='valor_por_defecto', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(default='temporal@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_usuario',
            field=models.CharField(default='usuario_temporal', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primer_apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segundo_apellido',
            field=models.CharField(max_length=100),
        ),
    ]
